gtests: net: packetdrill: run_all: fix print
Complaining that print is missing parentheses.

  File \". packetdrill run_all.py\", line 114
    print 'stdout: '
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print'stdout: '?

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>